### ISSUE TITLE
Captcha not usable for blind people.

### ISSUE THREAD

**Issue by LeifAndersen** [schneidmaster/gitreports.com#116] opened 2017-05-18 14:29 UTC
The captcha used in this form is not usable for blind/low-vision users. Would it be possible to contain a backup (audio based) captcha for people with low vision?

(One possibility is to use a third party captcha service for these cases.)

**Comment by schneidmaster** [comment] 2017-05-18 14:43
Closing as duplicate of #115

**Closed by schneidmaster** 2017-05-18 14:43 UTC

**Comment by LeifAndersen** [comment] 2017-05-18 14:45
Ah, woops. I guess we submitted them at the same time. :)
