### ISSUE TITLE
No email to reach out to issue creators

### ISSUE THREAD

**Issue by scottx611x** [schneidmaster/gitreports.com#119] opened 2017-07-25 13:11 UTC
(First thanks for the great service!)

I'm currently not seeing any email information about the users who submit issues, unless they explicitly check the: `Public email (send in the issue body)` box.

Currently I'm recieving notification emails like this:
```
New issue submitted to repository XXXXX! View it here. To manage settings and notifications for this repository, visit here.
```

I could just be missing something, but I'm not sure how to remediate issues for these users if I can't contact them.

Thanks!

**Comment by schneidmaster** [comment] 2017-07-25 16:07
Hi -- the main purpose of this project is to allow reporting general bugs and issues affecting the project, not really for tech support or contacting individual users. They have the option of including their email if they'd like a followup but generally speaking the limitation you're noting is by design.

**Comment by scottx611x** [comment] 2017-07-25 17:39
@schneidmaster: Thanks for the speedy response! 
I wouldn't mind seeing a per repo configurable for requiring user emails in submissions in the future (at least including them in a notification email), but this isn't of dire need. I could work on this if you think it would be beneficial to those other than myself, otherwise feel free to close!

**Comment by schneidmaster** [comment] 2017-07-25 20:15
Hey no problem. The app used to send user emails by default, but a number of the service users are based in the EU and apparently that runs afoul of their privacy laws. But I would be happy to accept a PR to add a configuration setting requiring the email, as long as it's off-by-default and then can be enabled by users who don't have those problems.

I'm currently working on revamping a bunch of stuff (see the `revamp` branch) -- so if you do decide to implement the change, you should either base off of that branch, or wait a few days for me to get it in master, or else you might end up with a bunch of merge conflicts :)

**Comment by schneidmaster** [comment] 2017-07-30 22:25
Hey @scottx611x -- I've merged the revamp I mentioned into master so I'm done making major code changes, feel free to send a PR if you're interested in adding this feature.

**Closed** 2017-08-01 14:49 UTC
Labels: feature
